

export const Argentina = () => ([
    { id: 'Buenos Aires', title: 'Buenos Aires' },
    { id: 'Catamarca   ', title: 'Catamarca   ' },
    { id: 'Chaco       ', title: 'Chaco       ' },
    { id: 'Chubut      ', title: 'Chubut      ' },
    { id: 'Córdoba     ', title: 'Córdoba     ' },
    { id: 'Corrientes  ', title: 'Corrientes  ' },
    { id: 'Entre Ríos  ', title: 'Entre Ríos  ' },
    { id: 'Formosa     ', title: 'Formosa     ' },
    { id: 'Jujuy       ', title: 'Jujuy       ' },
    { id: 'La Pampa', title: 'La Pampa' },
    { id: 'La Rioja', title: 'La Rioja' },
    { id: 'Mendoza ', title: 'Mendoza ' },
    { id: 'Misiones', title: 'Misiones' },
    { id: 'Neuquén ', title: 'Neuquén ' },
    { id: 'Río Negro', title: 'Río Negro' },
    { id: 'Salta', title: 'Salta' },
    { id: 'San Juan', title: 'San Juan' },
    { id: 'San Luis', title: 'San Luis' },
    { id: 'Santa Cruz', title: 'Santa Cruz' },
    { id: 'Santa Fe', title: 'Santa Fe' },
    { id: 'Santiago del Estero', title: 'Santiago del Estero' },
    { id: 'Tierra del Fuego, Antártida e Isla del Atlántico Sur', title: 'Tierra del Fuego, Antártida e Isla del Atlántico Sur' },
    { id: 'Tucumán ', title: 'Tucumán ' },
])

export const Chile = () => ([
    { id: 'Región de Arica y Parinacota                       ', title: 'Región de Arica y Parinacota                       ' },
    { id: 'Región de Tarapacá                                 ', title: 'Región de Tarapacá                                 ' },
    { id: 'Región de Antofagasta                              ', title: 'Región de Antofagasta                              ' },
    { id: 'Región de Atacama                                  ', title: 'Región de Atacama                                  ' },
    { id: 'Región de Coquimbo                                 ', title: 'Región de Coquimbo                                 ' },
    { id: 'Región de Valparaíso                               ', title: 'Región de Valparaíso                               ' },
    { id: 'Región Metropolitana de Santiago                   ', title: 'Región Metropolitana de Santiago                   ' },
    { id: 'Región del Libertador General Bernardo O’Higgins   ', title: 'Región del Libertador General Bernardo O’Higgins   ' },
    { id: 'Región del Maule                                   ', title: 'Región del Maule                                   ' },
    { id: 'Región del Ñuble                                   ', title: 'Región del Ñuble                                   ' },
    { id: 'Región del Biobío                                  ', title: 'Región del Biobío                                  ' },
    { id: 'Región de La Araucanía                             ', title: 'Región de La Araucanía                             ' },
    { id: 'Región de Los Ríos                                 ', title: 'Región de Los Ríos.                                 ' },
    { id: 'Región de Los Lagos                                ', title: 'Región de Los Lagos                                ' },
    { id: 'Región de Aysén del General Carlos Ibáñez del Campo', title: 'Región de Aysén del General Carlos Ibáñez del Campo' },
    { id: 'Región de Magallanes y la Antártica Chilena        ', title: 'Región de Magallanes y la Antártica Chilena        ' },

])

export const Colombia = () => ([
    { id: 'Amazonas                ', title: 'Amazonas                ' },
    { id: 'Antioquia               ', title: 'Antioquia               ' },
    { id: 'Arauca                  ', title: 'Arauca                  ' },
    { id: 'Atlántico               ', title: 'Atlántico               ' },
    { id: 'Bolívar                 ', title: 'Bolívar                 ' },
    { id: 'Boyacá                  ', title: 'Boyacá                  ' },
    { id: 'Caldas                  ', title: 'Caldas                  ' },
    { id: 'Caquetá                 ', title: 'Caquetá                 ' },
    { id: 'Casanare                ', title: 'Casanare                ' },
    { id: 'Cauca                   ', title: 'Cauca                   ' },
    { id: 'Cesar                   ', title: 'Cesar                   ' },
    { id: 'Chocó                   ', title: 'Chocó                   ' },
    { id: 'Córdoba                 ', title: 'Córdoba                 ' },
    { id: 'Cundinamarca            ', title: 'Cundinamarca            ' },
    { id: 'Guainía                 ', title: 'Guainía                 ' },
    { id: 'Guaviare                ', title: 'Guaviare                ' },
    { id: 'Huila                   ', title: 'Huila                   ' },
    { id: 'La Guajira              ', title: 'La Guajira              ' },
    { id: 'Magdalena               ', title: 'Magdalena               ' },
    { id: 'Meta                    ', title: 'Meta                    ' },
    { id: 'Nariño                  ', title: 'Nariño                  ' },
    { id: 'Norte de Santander      ', title: 'Norte de Santander      ' },
    { id: 'Putumayo                ', title: 'Putumayo                ' },
    { id: 'Quindío                 ', title: 'Quindío                 ' },
    { id: 'Risaralda               ', title: 'Risaralda               ' },
    { id: 'San Andrés y Providencia', title: 'San Andrés y Providencia' },
    { id: 'Santander               ', title: 'Santander               ' },
    { id: 'Sucre                   ', title: 'Sucre                   ' },
    { id: 'Tolima                  ', title: 'Tolima                  ' },
    { id: 'Valle del Cauca         ', title: 'Valle del Cauca         ' },
    { id: 'Vaupés                  ', title: 'Vaupés                  ' },
    { id: 'Vichada                 ', title: 'Vichada                 ' },
])

export const Uruguay = () => ([
    { id: 'Artigas       ', title: 'Artigas       ' },
    { id: 'Canelones     ', title: 'Canelones     ' },
    { id: 'Cerro Largo   ', title: 'Cerro Largo   ' },
    { id: 'Colonia       ', title: 'Colonia       ' },
    { id: 'Durazno       ', title: 'Durazno       ' },
    { id: 'Flores        ', title: 'Flores        ' },
    { id: 'Florida       ', title: 'Florida       ' },
    { id: 'Lavalleja     ', title: 'Lavalleja     ' },
    { id: 'Maldonado     ', title: 'Maldonado     ' },
    { id: 'Montevideo    ', title: 'Montevideo    ' },
    { id: 'Paysandú      ', title: 'Paysandú      ' },
    { id: 'Río Negro     ', title: 'Río Negro     ' },
    { id: 'Rivera        ', title: 'Rivera        ' },
    { id: 'Rocha         ', title: 'Rocha         ' },
    { id: 'Salto         ', title: 'Salto         ' },
    { id: 'San José      ', title: 'San José      ' },
    { id: 'Soriano       ', title: 'Soriano       ' },
    { id: 'Tacuarembó    ', title: 'Tacuarembó    ' },
    { id: 'Treinta y Tres', title: 'Treinta y Tres' },

])